export interface Emprendimiento {
  id: string;
  nombre: string;
  empresa: string;
  rubro: string;
  descripcion: string;
  direccion: string;
  telefono: string;
  instagram: string;
  descuento: string;
  otros: string;
  categoria: string;
  destacado?: boolean;
}

export const categorias = [
  { id: "todos", label: "Todos", icon: "grid" },
  { id: "deportivo", label: "Deportivo", icon: "dumbbell" },
  { id: "salud", label: "Salud & Bienestar", icon: "heart" },
  { id: "gastronomia", label: "Gastronomía", icon: "utensils" },
  { id: "tecnologia", label: "Tecnología", icon: "laptop" },
  { id: "moda", label: "Moda & Diseño", icon: "shirt" },
  { id: "hogar", label: "Hogar & Construcción", icon: "home" },
  { id: "mascotas", label: "Mascotas", icon: "paw" },
  { id: "servicios", label: "Servicios", icon: "briefcase" },
] as const;

export const emprendimientos: Emprendimiento[] = [
  {
    id: "1",
    nombre: "Johana y Damian",
    empresa: "Aconcagua",
    rubro: "Indumentaria Deportiva",
    descripcion: "Productos y ropa deportiva. Trail - Ciclismo - Triatlón - Running",
    direccion: "Adolfo Guemes 493",
    telefono: "",
    instagram: "aconcaguaindumentaria",
    descuento: "10% por ser familia AR en todo el local",
    otros: "",
    categoria: "deportivo",
    destacado: true,
  },
  {
    id: "2",
    nombre: "Rochi Cabolo",
    empresa: "CADICH",
    rubro: "Piezas de autor en cuero",
    descripcion: "Ropa y accesorios de cuero hechos a mano EN SALTA. Diseños personalizados.",
    direccion: "Atelier - Pasaje Mollinedo 427 (con cita previa)",
    telefono: "3875320318",
    instagram: "cadich.rcr",
    descuento: "",
    otros: "Diseños personalizados",
    categoria: "moda",
  },
  {
    id: "3",
    nombre: "Mili Burgos",
    empresa: "Push Sport",
    rubro: "Productos deportivos",
    descripcion: "Suplementos e indumentaria deportiva",
    direccion: "",
    telefono: "3875792395",
    instagram: "push_sportsalta",
    descuento: "10% por ser familia AR en efectivo",
    otros: "Envíos a domicilio",
    categoria: "deportivo",
  },
  {
    id: "4",
    nombre: "Carlita Rivella",
    empresa: "Nutrite Saludable",
    rubro: "Nutricionista",
    descripcion: "Educación alimentaria, venta de geles, gomitas, productos saludables y suplementos",
    direccion: "",
    telefono: "3876831480",
    instagram: "nutrite_saludable",
    descuento: "Descuento familia AR: 10% en consultas nutricionales y planificación de carreras. 10% en suplementos a partir de $50.000",
    otros: "Consultorio presencial Y online",
    categoria: "salud",
    destacado: true,
  },
  {
    id: "5",
    nombre: "Angui Rodriguez",
    empresa: "Fisioterapia",
    rubro: "Rehabilitación de ATM (bruxismo)",
    descripcion: "Tratamientos para Traumatologías, respiratorias, acupuntura y más. Kinesióloga - Rehabilitación deportiva.",
    direccion: "Cemid: Santa Fe 35",
    telefono: "3873412086",
    instagram: "Angelinarodriguezalvarez",
    descuento: "Descuento por ser familia AR",
    otros: "",
    categoria: "salud",
  },
  {
    id: "6",
    nombre: "Bren",
    empresa: "Lic. Psicomotricidad",
    rubro: "Psicomotricidad",
    descripcion: "Ayuda con jóvenes y adultos con discapacidades. Orientación en la búsqueda de una buena institución o profesionales afines.",
    direccion: "",
    telefono: "3875482027",
    instagram: "",
    descuento: "",
    otros: "",
    categoria: "salud",
  },
  {
    id: "7",
    nombre: "Flor y Mandi",
    empresa: "RAM Performance Gym",
    rubro: "Gimnasio",
    descripcion: "Gimnasio funcional - CARDIO y fuerza. Entrenamientos personalizados. ACÁ COMIENZA TU EVOLUCIÓN COMO CORREDOR",
    direccion: "Pasaje Ruiz de los Llanos 1335",
    telefono: "",
    instagram: "ramperformance",
    descuento: "Descuento por ser familia AR",
    otros: "",
    categoria: "deportivo",
    /* destacado: true, */
  },
  {
    id: "8",
    nombre: "Andy Guzman",
    empresa: "A.G Salud Integral",
    rubro: "Estética y Salud",
    descripcion: "Peeling (cuidado de la piel), labios, caída del cabello, papada, verrugas, elimina grasa localizada, secuelas de acné, glúteos",
    direccion: "Constancio Vigil 25 - B° San José Zona Oeste Baja",
    telefono: "3875478280",
    instagram: "ag_salud_integral",
    descuento: "",
    otros: "Espacio atendido por profesionales de la salud",
    categoria: "salud",
  },
  {
    id: "9",
    nombre: "Ade Fernandez",
    empresa: "Bye Vello",
    rubro: "Depilación definitiva láser",
    descripcion: "Depilación definitiva láser unisex",
    direccion: "Av. Mariano Moreno - B° Inter Sindical",
    telefono: "3872208088",
    instagram: "byevello.depilacion",
    descuento: "10% por ser familia AR en depilación",
    otros: "",
    categoria: "salud",
  },
  {
    id: "10",
    nombre: "Ade Fernandez",
    empresa: "Liss Salta",
    rubro: "Tratamientos capilares",
    descripcion: "Alisados profesionales",
    direccion: "",
    telefono: "3872208088",
    instagram: "liss.salta",
    descuento: "10% por ser familia AR en tratamientos capilares",
    otros: "",
    categoria: "salud",
  },
  {
    id: "11",
    nombre: "Diego Flores",
    empresa: "Bike Happy",
    rubro: "Bicicletería - Service",
    descripcion: "Especialización en MTB, ruta, triatlón, reparación y mantenimiento. Service de horquillas de suspensión y service en general.",
    direccion: "Av. Bolivia 2354",
    telefono: "3874661588",
    instagram: "bike.happy.service",
    descuento: "",
    otros: "",
    categoria: "deportivo",
    destacado: true,
  },
  {
    id: "12",
    nombre: "Nahuel Serrudo",
    empresa: "JNSIX",
    rubro: "Desarrollo de software y consultoría informática",
    descripcion: "Gestion y desarrollo de proyectos informaticos, creación de APP, web, sistemas. Tu arquitecto digital - Convertí tus ideas en soluciones informáticas.",
    direccion: "",
    telefono: "3875145165",
    instagram: "",
    descuento: "",
    otros: "",
    categoria: "tecnologia",
    destacado: true,
  },
  {
    id: "13",
    nombre: "Lic. Gabi Fossatti",
    empresa: "Asesorías de Empleabilidad",
    rubro: "Coaching laboral",
    descripcion: "Te ayudo a mejorar tu CV, prepararte para entrevistas y potenciar tu perfil profesional para encontrar mejores oportunidades.",
    direccion: "",
    telefono: "3816249385",
    instagram: "",
    descuento: "",
    otros: "",
    categoria: "servicios",
  },
  {
    id: "14",
    nombre: "Lore",
    empresa: "Diseñadora Gráfica",
    rubro: "Diseño gráfico",
    descripcion: "Servicios de diseño gráfico profesional",
    direccion: "",
    telefono: "3876116118",
    instagram: "",
    descuento: "",
    otros: "",
    categoria: "servicios",
  },
  {
    id: "15",
    nombre: "Gise",
    empresa: "Chiki Budines",
    rubro: "Pastelería saludable",
    descripcion: "Budines saludables y clásicos (350g y 400g). Limón, naranja, vainilla, marmolados, de avena, integrales, manzana, zanahoria, sin huevo, leche de almendras Y MÁS.",
    direccion: "",
    telefono: "3874123440",
    instagram: "chikibudinesymas",
    descuento: "",
    otros: "",
    categoria: "gastronomia",
  },
  {
    id: "16",
    nombre: "Agostina Ferreira",
    empresa: "Rústico Salta",
    rubro: "Panadería artesanal",
    descripcion: "Productos de panadería dulces y salados, pastelería, tartas, alfajores, maicenas. Panes de masa madre.",
    direccion: "Martina Silva de Gurruchaga 115 - 08 a 13hs y 17 a 21hs",
    telefono: "",
    instagram: "rusticosalta",
    descuento: "10% por ser familia AR en todos los productos",
    otros: "",
    categoria: "gastronomia",
    /* destacado: true, */
  },
  {
    id: "17",
    nombre: "Flor Ruiz",
    empresa: "Ula Ula Veggie",
    rubro: "Comida vegetariana",
    descripcion: "Comidas vegetarianas congeladas, yogur griego. Alimentación rica, saludable y consistente.",
    direccion: "",
    telefono: "3875160778",
    instagram: "ulaula.vaggie",
    descuento: "",
    otros: "",
    categoria: "gastronomia",
  },
  {
    id: "18",
    nombre: "Carlitos",
    empresa: "Alimentos Plaza Alvarado",
    rubro: "Alimentos para mascotas",
    descripcion: "Alimentos y artículos para mascotas. Los mejores precios y marcas.",
    direccion: "Caseros 1868",
    telefono: "3875657089 / 3874061023",
    instagram: "",
    descuento: "",
    otros: "",
    categoria: "mascotas",
  },
  {
    id: "19",
    nombre: "Mer Issa Aguirre",
    empresa: "Médica Veterinaria",
    rubro: "Veterinaria (M.P 615)",
    descripcion: "Consultas clínicas, esterilizaciones, asesoramiento nutricional, plan sanitario, vacunas y desparasitación. Atención en domicilio y veterinaria.",
    direccion: "Veterinaria Walter Chian - 10 de Octubre 402",
    telefono: "3874890111",
    instagram: "",
    descuento: "",
    otros: "Lunes y Martes 9 a 15hs, Sábados 14 a 20:30hs",
    categoria: "mascotas",
  },
  {
    id: "20",
    nombre: "Dany Rivero",
    empresa: "Emma Deco Home",
    rubro: "Decoración del hogar",
    descripcion: "Almohadones, cortinas de baño, caminos de mesa, manteles, cubre sommier y más.",
    direccion: "",
    telefono: "3874880965",
    instagram: "emmadecohome",
    descuento: "10% por ser familia AR en todo",
    otros: "Ventas por mayor y menor",
    categoria: "hogar",
  },
  {
    id: "21",
    nombre: "Dani Rosas",
    empresa: "Arquitecta",
    rubro: "Arquitectura",
    descripcion: "Consultas en general",
    direccion: "",
    telefono: "3875677247",
    instagram: "",
    descuento: "",
    otros: "",
    categoria: "hogar",
  },
  {
    id: "22",
    nombre: "Rogelio Subia",
    empresa: "MVA Construcción",
    rubro: "Construcción en seco y pintura",
    descripcion: "Steel frame, durlock, PVC, pisos flotantes, desmontables, cielo raso, muebles, figuras en paredes. TRABAJOS DE PINTURA EN GRAL.",
    direccion: "",
    telefono: "3872126501",
    instagram: "",
    descuento: "",
    otros: "Presupuestos sin cargo",
    categoria: "hogar",
  },
  {
    id: "23",
    nombre: "Rochi Cabolo",
    empresa: "Cuadros y Láminas",
    rubro: "Arte",
    descripcion: "Pinturas inspiradas 100% en la naturaleza. Pinceladas sueltas y desprolijas. Cada pintura es única e irrepetible.",
    direccion: "Atelier - Pasaje Mollinedo 427 (con cita previa)",
    telefono: "3875320318",
    instagram: "rocavolor",
    descuento: "",
    otros: "",
    categoria: "moda",
  },
  {
    id: "24",
    nombre: "Ade Fernandez",
    empresa: "iCellStoreX",
    rubro: "Tecnología Apple/Samsung",
    descripcion: "Tienda de iPhone y Samsung, MacBook, iPad, Apple Watch",
    direccion: "Av. Belgrano 2387",
    telefono: "",
    instagram: "icellstorex",
    descuento: "10% por ser familia AR en compra de equipos y accesorios",
    otros: "",
    categoria: "tecnologia",
  },
];

// Campos sugeridos para solicitar a los emprendedores
export const camposSugeridos = [
  { campo: "Logo o imagen", descripcion: "Imagen representativa del emprendimiento (formato JPG/PNG)" },
  { campo: "Email de contacto", descripcion: "Correo electrónico para consultas" },
  { campo: "Sitio web", descripcion: "URL del sitio web si tienen" },
  { campo: "Horarios de atención", descripcion: "Días y horarios de atención al público" },
  { campo: "Métodos de pago", descripcion: "Efectivo, transferencia, tarjetas, etc." },
  { campo: "Zona de cobertura", descripcion: "Si hacen envíos, a qué zonas llegan" },
  { campo: "Especialidades", descripcion: "Productos o servicios más destacados" },
  { campo: "Años de experiencia", descripcion: "Tiempo en el mercado" },
  { campo: "Certificaciones", descripcion: "Matrículas, títulos o certificaciones relevantes" },
];
